### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by mewluee** [mewluee/todo-app#4]
### 기능
- todo 등록 기능
- todo 삭제 기능
- todo 조회 기능
- todo 수정 기능(done 여부)

### 해야할 일
1. [ ] 컨트롤러와 서비스 기본 틀 구성하기
2. [ ] DB 테이블 구현하기
3. [ ] 레포지토리 구성하기
4. [ ] 테스트 코드 짜기
5. [ ] 부가 기능 생각하기

### 예상 작업 시간
구현 2h
테스트 1h
기타 문서 작업 1h 
블로깅 1h
